### ISSUE TITLE
Can Attiny 3266-SU be replaced with something else?

### ISSUE THREAD

**Issue by myseil** [hb020/batterymeter#1]
Hi,
Attiny 3266-SU is not easy to buy in China, can it be replaced by others? Such as STM microcontroller.

**Comment by hb020** [comment]
Any other form factor atttiny 3226 or 3227 would also do. I lately found the versions in VQFN easier to source than SOIC. 

But yes, STM might also do. 
Hard requirement: differential ADC 12 bits or more, 100ksps or more.

**Comment by myseil** [comment]
> 

Thanks Reply! I'll give it a try, atttiny microcontrollers are not easy to buy in China. I wonder whether to find a general-purpose microcontroller to replace it.
